services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data
    networks:
      - dev-network

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - dev-network

volumes:
  postgres-dev-data:
  redis-dev-data:

networks:
  dev-network:
    driver: bridge
